services:
  - type: web
    name: shopflow-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: fincore-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: fincore-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: fincore-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: fincore-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fincore-postgres
          property: password
